local E, L, V, P, G = unpack(ElvUI); --Import: Engine, Locales, PrivateDB, ProfileDB, GlobalDB

P.gridSize = 64
P.farmSize = 340

--Core
P["general"] = {
	["taintLog"] = false,
	["stickyFrames"] = true,
	["loginmessage"] = true,
	["autoRepair"] = "NONE",
	["autoRoll"] = false,
	["vendorGrays"] = false,
	["autoAcceptInvite"] = false,
	["bottomPanel"] = true,
	["hideErrorFrame"] = true,
	["enhancedPvpMessages"] = true,
	["numberPrefixStyle"] = "ENGLISH",
	["fontSize"] = 12,
	["font"] = "PT Sans Narrow",

	["bordercolor"] = {r = 0, g = 0, b = 0},
	["backdropcolor"] = {r = 0.1, g = 0.1, b = 0.1},
	["backdropfadecolor"] = {r = .06, g = .06, b = .06, a = 0.8},
	["valuecolor"] = {r = 254/255, g = 123/255, b = 44/255},

	["minimap"] = {
		["size"] = 176,
		["locationText"] = "MOUSEOVER",
		["locationFontSize"] = 12,
		["locationFontOutline"] = "OUTLINE",
		["locationFont"] = "PT Sans Narrow",
		["resetZoom"] = {
			["enable"] = false,
			["time"] = 3,
		},
		["icons"] = {
			["calendar"] = {
				["scale"] = 1,
				["position"] = "TOPRIGHT",
				["xOffset"] = 0,
				["yOffset"] = 0,
				["hide"] = true,
			},
			["mail"] = {
				["scale"] = 1,
				["position"] = "TOPRIGHT",
				["xOffset"] = 3,
				["yOffset"] = 4,
			},
			["lfgEye"] = {
				["scale"] = 1,
				["position"] = "BOTTOMRIGHT",
				["xOffset"] = 3,
				["yOffset"] = 0,
			},
			["battlefield"] = {
				["scale"] = 1,
				["position"] = "BOTTOMRIGHT",
				["xOffset"] = 3,
				["yOffset"] = 0,
			},
			["difficulty"] = {
				["scale"] = 1,
				["position"] = "TOPLEFT",
				["xOffset"] = 0,
				["yOffset"] = 0,
			},
			["vehicleLeave"] = {
				["scale"] = 1,
				["position"] = "BOTTOMLEFT",
				["xOffset"] = 2,
				["yOffset"] = 2,
				["hide"] = false,
			},
		}
	},
}

-- Data Bars
P["databars"] = {
	["experience"] = {
		["enable"] = true,
		["width"] = 10,
		["height"] = 180,
		["textFormat"] = "NONE",
		["textSize"] = 12,
		["font"] = "PT Sans Narrow",
		["fontOutline"] = "NONE",
		["mouseover"] = false,
		["orientation"] = "VERTICAL",
		["hideAtMaxLevel"] = true,
	},
	["reputation"] = {
		["enable"] = true,
		["width"] = 10,
		["height"] = 180,
		["textFormat"] = "NONE",
		["textSize"] = 12,
		["font"] = "PT Sans Narrow",
		["fontOutline"] = "NONE",
		["mouseover"] = false,
		["orientation"] = "VERTICAL",
	},
}

--Chat
P["chat"] = {
	["lockPositions"] = true,
	["url"] = true,
	["shortChannels"] = true,
	["hyperlinkHover"] = true,
	["throttleInterval"] = 45,
	["scrollDownInterval"] = 15,
	["fade"] = true,
	["font"] = "PT Sans Narrow",
	["fontOutline"] = "NONE",
	["sticky"] = true,
	["emotionIcons"] = true,
	["keywordSound"] = "None",
	["whisperSound"] = "Whisper Alert",
	["noAlertInCombat"] = false,
	["chatHistory"] = true,
	["timeStampFormat"] = "NONE",
	["keywords"] = "ElvUI",
	["separateSizes"] = false,
	["panelWidth"] = 412,
	["panelHeight"] = 180,
	["panelWidthRight"] = 412,
	["panelHeightRight"] = 180,
	["panelBackdropNameLeft"] = "",
	["panelBackdropNameRight"] = "",
	["panelBackdrop"] = "SHOWBOTH",
	["panelTabBackdrop"] = false,
	["panelTabTransparency"] = false,
	["editBoxPosition"] = "BELOW_CHAT",
	["fadeUndockedTabs"] = true,
	["fadeTabsNoBackdrop"] = true,
	["useAltKey"] = false,
	["classColorMentionsChat"] = true,
	["numAllowedCombatRepeat"] = 5,
	["useCustomTimeColor"] = true,
	["customTimeColor"] = {r = 0.7, g = 0.7, b = 0.7},
	["numScrollMessages"] = 3,

	["tabFont"] = "PT Sans Narrow",
	["tabFontSize"] = 12,
	["tabFontOutline"] = "NONE",
}

--Datatexts
P["datatexts"] = {
	["font"] = "PT Sans Narrow",
	["fontSize"] = 12,
	["fontOutline"] = "NONE",
	["wordWrap"] = false,

	["panels"] = {
		["LeftChatDataPanel"] = {
			["left"] = "Armor",
			["middle"] = "Durability",
			["right"] = "Avoidance",
		},
		["RightChatDataPanel"] = {
			["left"] = "System",
			["middle"] = "Time",
			["right"] = "Gold",
		},
		["LeftMiniPanel"] = "Guild",
		["RightMiniPanel"] = "Friends",
		["BottomMiniPanel"] = "",
		["TopMiniPanel"] = "",
		["BottomLeftMiniPanel"] = "",
		["BottomRightMiniPanel"] = "",
		["TopRightMiniPanel"] = "",
		["TopLeftMiniPanel"] = "",
	},
	["battleground"] = true,
	["panelTransparency"] = false,
	["panelBackdrop"] = true,

	--Datatext Options
	--General
	["goldFormat"] = "BLIZZARD",
	["goldCoins"] = false,
	--Time Datatext
	["timeFormat"] = "%I:%M",
	["dateFormat"] = "",

	--Enabled/Disabled Panels
	["minimapPanels"] = true,
	["leftChatPanel"] = true,
	["rightChatPanel"] = true,
	["minimapTop"] = false,
	["minimapTopLeft"] = false,
	["minimapTopRight"] = false,
	["minimapBottom"] = false,
	["minimapBottomLeft"] = false,
	["minimapBottomRight"] = false,
}

--Tooltip
P["tooltip"] = {
	["cursorAnchor"] = false,
	["targetInfo"] = true,
	["playerTitles"] = true,
	["guildRanks"] = true,
	["inspectInfo"] = true,
	["itemCount"] = "BAGS_ONLY",
	["spellID"] = true,
	["font"] = "PT Sans Narrow",
	["fontOutline"] = "NONE",
	["headerFontSize"] = 12,
	["textFontSize"] = 12,
	["smallTextFontSize"] = 12,
	["colorAlpha"] = 0.8,
	["visibility"] = {
		["unitFrames"] = "NONE",
		["bags"] = "NONE",
		["actionbars"] = "NONE",
		["combat"] = false
	},
	["healthBar"] = {
		["text"] = true,
		["height"] = 7,
		["font"] = "Homespun",
		["fontSize"] = 10,
		["fontOutline"] = "OUTLINE",
		["statusPosition"] = "BOTTOM",
	},
	["useCustomFactionColors"] = false,
	["factionColors"] = {
		[1] = {r = 0.8, g = 0.3, b = 0.22},
		[2] = {r = 0.8, g = 0.3, b = 0.22},
		[3] = {r = 0.75, g = 0.27, b = 0},
		[4] = {r = 0.9, g = 0.7, b = 0},
		[5] = {r = 0, g = 0.6, b = 0.1},
		[6] = {r = 0, g = 0.6, b = 0.1},
		[7] = {r = 0, g = 0.6, b = 0.1},
		[8] = {r = 0, g = 0.6, b = 0.1},
	}
}

P["cooldown"] = {
	threshold = 3,
	expiringColor = {r = 1, g = 0, b = 0},
	secondsColor = {r = 1, g = 1, b = 0},
	minutesColor = {r = 1, g = 1, b = 1},
	hoursColor = {r = 0.4, g = 1, b = 1},
	daysColor = {r = 0.4, g = 0.4, b = 1},
}

--Actionbar
P["actionbar"] = {
	["font"] = "Homespun",
	["fontSize"] = 10,
	["fontOutline"] = "MONOCHROMEOUTLINE",
	["fontColor"] = {r = 1, g = 1, b = 1},

	["macrotext"] = false,
	["hotkeytext"] = true,

	["noRangeColor"] = {r = 0.8, g = 0.1, b = 0.1},
	["noPowerColor"] = {r = 0.5, g = 0.5, b = 1},
	["usableColor"] = {r = 1, g = 1, b = 1},
	["notUsableColor"] = {r = 0.4, g = 0.4, b = 0.4},

	["keyDown"] = true,
	["movementModifier"] = "SHIFT",

	["microbar"] = {
		["enabled"] = false,
		["Scale"] = 1,
		["xOffset"] = 1,
		["yOffset"] = 1,
		["buttonsPerRow"] = 10,
		["alpha"] = 1,
		["mouseover"] = false
	},

	["globalFadeAlpha"] = 0,
	["lockActionBars"] = true,

	["bar1"] = {
		["enabled"] = true,
		["buttons"] = 12,
		["mouseover"] = false,
		["buttonsPerRow"] = 12,
		["point"] = "BOTTOMLEFT",
		["backdrop"] = false,
		["heightMult"] = 1,
		["widthMult"] = 1,
		["buttonsize"] = 32,
		["buttonspacing"] = 2,
		["backdropSpacing"] = 2,
		["alpha"] = 1,
		["showGrid"] = true,
	},
	["bar2"] = {
		["enabled"] = false,
		["mouseover"] = false,
		["buttons"] = 12,
		["buttonsPerRow"] = 12,
		["point"] = "BOTTOMLEFT",
		["backdrop"] = false,
		["heightMult"] = 1,
		["widthMult"] = 1,
		["buttonsize"] = 32,
		["buttonspacing"] = 2,
		["backdropSpacing"] = 2,
		["alpha"] = 1,
		["showGrid"] = true,
	},
	["bar3"] = {
		["enabled"] = true,
		["mouseover"] = false,
		["buttons"] = 6,
		["buttonsPerRow"] = 6,
		["point"] = "BOTTOMLEFT",
		["backdrop"] = false,
		["heightMult"] = 1,
		["widthMult"] = 1,
		["buttonsize"] = 32,
		["buttonspacing"] = 2,
		["backdropSpacing"] = 2,
		["alpha"] = 1,
		["showGrid"] = true,
	},
	["bar4"] = {
		["enabled"] = true,
		["mouseover"] = false,
		["buttons"] = 12,
		["buttonsPerRow"] = 1,
		["point"] = "TOPRIGHT",
		["backdrop"] = true,
		["heightMult"] = 1,
		["widthMult"] = 1,
		["buttonsize"] = 32,
		["buttonspacing"] = 2,
		["backdropSpacing"] = 2,
		["alpha"] = 1,
		["showGrid"] = true,
	},
	["bar5"] = {
		["enabled"] = true,
		["mouseover"] = false,
		["buttons"] = 6,
		["buttonsPerRow"] = 6,
		["point"] = "BOTTOMLEFT",
		["backdrop"] = false,
		["heightMult"] = 1,
		["widthMult"] = 1,
		["buttonsize"] = 32,
		["buttonspacing"] = 2,
		["backdropSpacing"] = 2,
		["alpha"] = 1,
		["showGrid"] = true,
	},
	["bar6"] = {
		["enabled"] = false,
		["mouseover"] = false,
		["buttons"] = 12,
		["buttonsPerRow"] = 12,
		["point"] = "BOTTOMLEFT",
		["backdrop"] = false,
		["heightMult"] = 1,
		["widthMult"] = 1,
		["buttonsize"] = 32,
		["buttonspacing"] = 2,
		["backdropSpacing"] = 2,
		["alpha"] = 1,
		["showGrid"] = true,
	},
	["barPet"] = {
		["enabled"] = true,
		["mouseover"] = false,
		["buttons"] = NUM_PET_ACTION_SLOTS,
		["buttonsPerRow"] = 1,
		["point"] = "TOPRIGHT",
		["backdrop"] = true,
		["heightMult"] = 1,
		["widthMult"] = 1,
		["buttonsize"] = 32,
		["buttonspacing"] = 2,
		["backdropSpacing"] = 2,
		["alpha"] = 1,
	},
	["barShapeShift"] = {
		["enabled"] = true,
		["style"] = "darkenInactive",
		["mouseover"] = false,
		["buttonsPerRow"] = NUM_SHAPESHIFT_SLOTS,
		["buttons"] = NUM_SHAPESHIFT_SLOTS,
		["point"] = "TOPLEFT",
		["backdrop"] = false,
		["heightMult"] = 1,
		["widthMult"] = 1,
		["buttonsize"] = 32,
		["buttonspacing"] = 2,
		["backdropSpacing"] = 2,
		["alpha"] = 1,
	},
}