local LSM = LibStub("LibSharedMedia-3.0")

if LSM == nil then return end

LSM:Register("statusbar", "ElvUI Gloss", "Interface\\AddOns\\ElvUI\\Media\\Textures\\normTex.tga")
LSM:Register("statusbar", "ElvUI Norm", "Interface\\AddOns\\ElvUI\\Media\\Textures\\normTex2.tga")
LSM:Register("statusbar", "Minimalist", "Interface\\AddOns\\ElvUI\\Media\\Textures\\Minimalist.tga")
LSM:Register("statusbar", "ElvUI Blank", "Interface\\BUTTONS\\WHITE8X8")
LSM:Register("background", "ElvUI Blank", "Interface\\BUTTONS\\WHITE8X8")
LSM:Register("border", "ElvUI GlowBorder", "Interface\\AddOns\\ElvUI\\Media\\Textures\\glowTex.tga")
LSM:Register("font", "Continuum Medium", "Interface\\AddOns\\ElvUI\\Media\\Fonts\\Continuum_Medium.ttf")
LSM:Register("font", "Die Die Die!", "Interface\\AddOns\\ElvUI\\Media\\Fonts\\DieDieDie.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Action Man", "Interface\\AddOns\\ElvUI\\Media\\Fonts\\Action_Man.ttf")
LSM:Register("font", "Expressway", "Interface\\AddOns\\ElvUI\\Media\\Fonts\\Expressway.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "PT Sans Narrow", "Interface\\AddOns\\ElvUI\\Media\\Fonts\\PT_Sans_Narrow.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Homespun", "Interface\\AddOns\\ElvUI\\Media\\Fonts\\Homespun.ttf",LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("sound", "ElvUI Aska", "Interface\\AddOns\\ElvUI\\Media\\Sounds\\sndIncMsg.ogg")
LSM:Register("sound", "Awww Crap", "Interface\\AddOns\\ElvUI\\Media\\Sounds\\awwcrap.ogg")
LSM:Register("sound", "BBQ Ass", "Interface\\AddOns\\ElvUI\\Media\\Sounds\\bbqass.ogg")
LSM:Register("sound", "Big Yankie Devil", "Interface\\AddOns\\ElvUI\\Media\\Sounds\\yankiebangbang.ogg")
LSM:Register("sound", "Dumb Shit", "Interface\\AddOns\\ElvUI\\Media\\Sounds\\dumbshit.ogg")
LSM:Register("sound", "Mama Weekends", "Interface\\AddOns\\ElvUI\\Media\\Sounds\\mamaweekends.ogg")
LSM:Register("sound", "Runaway Fast", "Interface\\AddOns\\ElvUI\\Media\\Sounds\\runfast.ogg")
LSM:Register("sound", "Stop Running", "Interface\\AddOns\\ElvUI\\Media\\Sounds\\stoprunningslimball.ogg")
LSM:Register("sound", "Warning", "Interface\\AddOns\\ElvUI\\Media\\Sounds\\warning.ogg")
LSM:Register("sound", "Whisper Alert", "Interface\\AddOns\\ElvUI\\Media\\Sounds\\whisper.ogg")